server:
  port: 8020

eureka:
  instance:
    hostname: https://walletservice-ikcz.onrender.com
  client:
    serviceUrl:
      defaultZone: https://bankatii-discovery-server.onrender.com
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
